Feat : 공통 컴포넌트(상단 바) 제작
goormthon-Univ/2024_BEOTKKOTTHON_TEAM_33_FE pull request #4
Opened 2024-03-19 08:17 UTC by JaeHyun137

### PR Type
<!— Please check the one that applies to this PR using "x". —>

- [X ] 기능개발(Feature)
- [ ] 버그수정(Bugfix)
- [X] css 등 ui 스타일링 관련 변경,추가사항
- [ ] 코드 스타일 변경(Code style update) (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경
- [ ] 문서 내용 변경
- [ ] Other… Please describe:

### Issue Number or Link
#1 

### 요약(Summary)
1) 컴포넌트 3개 (기억해봄+로고 버전(1) / 이전버튼+텍스트 버전(2)/ 텍스트 ONLY 버전(3))

### 상세 내용(Describe your changes)
1) 기억해봄+로고 버전 컴포넌트 하나, 나머지 두개는 컴포넌트 공유
2) 묘한 수평 안맞음 해결됨 
3) 호출시에 버튼타입(3 버전 중 뭔지) 랑 텍스트(중앙텍스트 있는경우) 주면 사용 가능 (근데 방금 생각났는데 1번 버전에선 텍스트 안줘도 되게 하는거 처리 안했다,,,, 담에 수정해둘게 사용하는덴 문제없어여)

### PR point (집중적으로 리뷰/피드백 받고 싶은 부분)
1) (2)+(3)을 한 컴포넌트로 합치려다가,,, 스타일이 자꾸 꼬여서 결국 두개를 합치긴 합쳤는데 1번 버전과 2+3번 버전 코드가 좀 중복되게 되었슴 (원래 헤더 wrapper+자식으로 헤더 컨텐츠 초합이었는데 wrapper 없앰)... 그치만 코드 양이 전에 비해 확 줄긴함
2) 스타일 적용 괜찮은지.. 위험해보이는 부분 (실제로 폰에 렌더링했을때 깨질것같다거나) 하는부분 없는지 봐주세여
3)지금은 텍스트 후보를 피그마에 있는 텍스트들 넣어놨는데.. 텍스트가 아직 확정이 아니고 바뀔수도 있고 하니 이걸 후보를 지정하지 말고 그냥 stiring으로 놓고 호출하는 곳에서 원하는 텍스트를 지정하도록 하는게 나을지 ? 상세내용-3) 이랑 함꼐 담에 수정하도록 할게여

### preview 이미지 혹은 영상 
1) 어제 카톡으로 전송했으니 패스~

2024-03-19 11:41 UTC, seungsimdang requested changes

2024-03-19 11:41 UTC, seungsimdang commented on src/components/HeaderNav/HeaderNav.styles.ts
> +top:0;
이런 레이아웃적인 요소들 코드 중복이 많은데 공통 레이아웃으로 빼면 좋을듯!!

2024-03-19 11:41 UTC, seungsimdang commented on src/components/HeaderNav/HeaderNav.styles.ts
> +/* background-color: yellow; */ //영역 체크용
필요없는 주석은 지워주세요~.~

2024-03-19 11:41 UTC, seungsimdang commented on src/components/HeaderNav/HeaderNav.styles.ts
> +`
헉 이거 div태그로 넣은거였어?? 이거는 개인적으로 폰트가 달라서 svg로 넣어두는것도 낫밷일듯!!

2024-03-19 11:41 UTC, seungsimdang commented on src/components/HeaderNav/HeaderNav.tsx
> +const Header: React.FC<HeaderProps> = ({ type,text }) => {
https://velog.io/@frombozztoang/React.FC-%EC%82%AC%EC%9A%A9-%EC%A7%80%EC%96%91%ED%95%98%EA%B8%B0

요기 참고해보면 좋을것가탕용ㅇㅇ

2024-03-19 11:41 UTC, seungsimdang commented on src/components/HeaderNav/HeaderNav.tsx
> +            <S.HeaderWithMiddleText><span>{text}</span></S.HeaderWithMiddleText>
이 부분 styled-component로 작성하지 않은 태그들은 이유가 있어서 그런걸까?

2024-03-19 11:41 UTC, seungsimdang commented on src/components/HeaderNav/HeaderNav.types.ts
> +}
밑에 interface와 안합치고 따로 뺀 이유가 있나용?

2024-03-19 11:41 UTC, seungsimdang commented on src/components/HeaderNav/HeaderNav.types.ts
> +  text: '해봄이' | '최근 사진' | '나른한 하루'|'나의 추억 기록함';
![image](https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_33_FE/assets/93538221/d577ad25-f32c-49eb-a63d-b7092e42368d)
이런 부분처럼 header의 title은 자주 바뀌는 부분이라 props로 특정 text만 지정하는것보다 children으로 넘기는게 조아보여요~~

2024-03-19 12:43 UTC, JaeHyun137 commented on src/components/HeaderNav/HeaderNav.styles.ts
> +top:0;
수정완료 ~

2024-03-19 12:43 UTC, JaeHyun137 commented on src/components/HeaderNav/HeaderNav.styles.ts
> +/* background-color: yellow; */ //영역 체크용
완료~

2024-03-19 12:43 UTC, JaeHyun137 commented on src/components/HeaderNav/HeaderNav.styles.ts
> +`
일단 pass .. 다른거 다 구현 완료 하고 시간나면 하겟삼 (주석으로 todo해둠)

2024-03-19 12:44 UTC, JaeHyun137 commented on src/components/HeaderNav/HeaderNav.tsx
> +const Header: React.FC<HeaderProps> = ({ type,text }) => {
이것도 일단 pass,, 위와 같이 해둠

2024-03-19 12:45 UTC, JaeHyun137 commented on src/components/HeaderNav/HeaderNav.tsx
> +            <S.HeaderWithMiddleText><span>{text}</span></S.HeaderWithMiddleText>
버튼은 아까 코어타임때 말한것처럼 스타일링이 없어서 일단 그렇게 해둠 /

2024-03-19 12:45 UTC, JaeHyun137 commented on src/components/HeaderNav/HeaderNav.types.ts
> +}
안쓸거라 삭제했서여

2024-03-19 12:45 UTC, JaeHyun137 commented on src/components/HeaderNav/HeaderNav.types.ts
> +  text: '해봄이' | '최근 사진' | '나른한 하루'|'나의 추억 기록함';
수정완료

2024-03-19 12:50 UTC, seungsimdang approved these changes

2024-03-19 12:51 UTC, merged

2024-03-20 06:57 UTC, JaeHyun137 commented on src/components/HeaderNav/HeaderNav.tsx
> +const Header: React.FC<HeaderProps> = ({ type,text }) => {
3/20 오후에 수정 완료했습니다 (아직 FC쓴 코드가 하나뿐이고, 나만 작업하는 파일(상단바)라서 그냥 지금 작업중인 브랜치에서 했서요

2024-03-20 07:03 UTC, JaeHyun137 commented on src/components/HeaderNav/HeaderNav.styles.ts
> +`
이거 svg로 바꿨어요 ~ 그랬더니 그 피그마 폰트로 적용됨 (03/20 오후 수정)